/**
 * Created by MZC01-YUNYEN on 2021-11-03.
 */

/**
 * this class is made for testing scratch orgs.
 * lets see if this could be deployed by scratch org in local environment
 * and by github push and jenkins! please work pleaseTT
 */
public with sharing class NewApexClass {

    public static Integer getZero(){
        return 0;
    }

    public static Integer getOne(){
        return 1;
    }

    //
}